### ISSUE TITLE
chapter 14 - request for clarifications

### ISSUE THREAD

**Issue by pdesterlich** [scotch-io/mean-machine-code#3]
Not a real issue, just a request for clarifications.

In chapter 14 (Mean Stack Application Structure) you move all api routing code in /app/routes/api.js ; i understand how it works, but there are two points i don't get:

in line 1 you require bodyparser

``` javascript
var bodyParser = require('body-parser'),
```

but `bodyParser` is never actually used in api.js

in line 9 you declare module exports passing app and express variables

``` javascript
module.exports = function(app, express) {
```

but `app` is never used in api.js

So my question is: are these two (bodyparser and app) needed in some ways without being explicitly called or can they be removed? If they are needed, then why?

**Comment by chris-sev** [comment]
Hello,

You are correct. Both `body-parser` and `app` do not need to be there. 

I mistakenly put `body-parser` in there because I thought it was necessary for `req.body.name` to work, but since we configured it with our main `app`, api.js will work without it.

I also like passing `app` into a routes file because you could also define routes directly on the `app` object instead of using `express.Router()`. I've clarified that in the book that it isn't used, but could be useful if you were to define routes on the `app` object.
