### ISSUE TITLE
About 09-node-api

### ISSUE THREAD

**Issue by kitomicms** [scotch-io/mean-machine-code#6]
![image](https://cloud.githubusercontent.com/assets/5723721/5937372/c180361c-a729-11e4-9220-de6742f851c0.png)
![image](https://cloud.githubusercontent.com/assets/5723721/5937400/1c89b4fc-a72a-11e4-85b5-614755f9190f.png)

Even though I follow exactly as the instruction in the book, I do not get the password shown up using Postman. It goes the same whether I use MongoLab or local database with Robomongo.

Any idea about this issue?

Thanks. 
Gary

**Comment by chris-sev** [comment]
Hey Gary,

Your application is working exactly as it should. The password shouldn't be
returned since we put select:false in the Mongoose User model.

I'm pushing an update to the book today to fix that image error.

Thanks.

_Chris Sevilleja | scotch.io http://scotch.io/_
@scotch_io http://twitter.com/scotch_io
@sevilayha http://twitter.com/sevilayha

**Comment by travisirby** [comment]
One other minor issue I ran into in this chapter was on page 73, line 27 of the code, the return statement is missing. This causes node to crash from a double callback if you try to change the username to one which is already taken. I see you have the proper code on github though.

Really enjoying the book!

**Comment by chris-sev** [comment]
Good catch. Somebody else pointed that out also and we pushed an update to the code and book to fix that issue today.

You can download the latest version from Leanpub now.
